org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.233
neo_version_range=[21.1.233,21.2)
loader_version_range=[4,)
mod_id=myriad_calamity
mod_name=\u4e07\u8c61\u707e\u5384
mod_license=All Rights Reserved
mod_version=0.9.4+mc1.21.1
mod_group_id=net.xuwu.myriadcalamity
mod_authors=lingmu
mod_description=\u4e07\u8c61\u707e\u5384\uff1a\u4ee5\u673a\u67a2\u821e\u8005\u53cc\u4eba\u6218\u63ed\u5f00\u5e8f\u5e55\u7684 Boss \u6a21\u7ec4\u3002
